// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihwpeqjavzvawjfydray.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlod3BlcWphdnp2YXdqZnlkcmF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTkzMjcsImV4cCI6MjA3MzMzNTMyN30.yxpZTJzO6-ny0TOySduFLYAqndZI6Oa0Vr_hBuIM52s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
